services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # INSTALLER
    #

    InSquare\PimcoreFaviconBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('InSquarePimcoreFaviconBundle')"

    InSquare\PimcoreFaviconBundle\Service\FaviconGenerator:
        arguments:
            $manifestName: '%in_square_pimcore_favicon.manifest_name%'
            $manifestBasePath: '%in_square_pimcore_favicon.manifest_base_path%'

    InSquare\PimcoreFaviconBundle\Twig\Extension\FaviconExtension:
        arguments:
            $themeColor: '%in_square_pimcore_favicon.theme_color%'
            $tileColor: '%in_square_pimcore_favicon.tile_color%'

    #
    # CONTROLLERS
    #

    InSquare\PimcoreFaviconBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    InSquare\PimcoreFaviconBundle\:
        resource: '../../'
        exclude:
            - '../../Controller/'
            - '../../DependencyInjection/'
            - '../../Installer.php'
            - '../../Resources/'
            - '../../Service/FaviconGenerator.php'
            - '../../Twig/Extension/FaviconExtension.php'
            - '../../InSquarePimcoreFaviconBundle.php'
